### ISSUE TITLE
Sorting causes Dexterity types to not show

### ISSUE THREAD

**Issue by 127001** [collective/collective.dancing#3]
I'm having an issue with the automated mailing in combination with dexterity types. When I configure my collection (still classic?) and test the collection by viewing it, all seems fine. The message is also fine when received.

But when I add a sorting on e.g. changed date or creation date (any date for that matter) problems start. Viewing the collection still works, but after sending the the collection shows no items.

Another collection in the same newsletter showing ATEvent items is working just fine.

Running Plone 4.2.5 and using the latest version from git for both collective.dancing and collective.singing.
If any addition info is needed, please tell me.

**Comment by frisi** [comment]
this is not dexterity problem at all. i had the same problems when sorting the results of collections by effectiveDate with archetypes.

this is what's happening:

if the collection has a sort criteria on effective `collective.dancing` adds an additional query argument to the collection's query.

see [the collector's get_items_for_topic method](https://github.com/collective/collective.dancing/blob/1.0/collective/dancing/collector.py#L172)

it will only return elements having an effective date after the cue date (last time this newlsetter has been sent to the recipient) and before now (see [this function](https://github.com/collective/collective.dancing/blob/1.0/collective/dancing/collector.py#L246))

i guess this is a nice feature for newsletters that are automatically sent in regular intervals (ie weekly). if i'm new to the newsletter, i'd also get items created two weeks ago.
existing users will not get the same items as they did a week ago. and possibly no newsletter at all (in the case there are not items matching the collections criteria which are newer than the last cue date).
however, in most cases this makes people wonder why they see items in the preview but they are not included in the newsletter (at least not for all recipients)

we should think of making this an option on the newsletter instead of implicitly binding this additional feature based on the collection's sort criteria.
